---
- hosts: all

  tasks:
  - name: Install Packages
    apt: name={{item}} state=present
    with_items:
      - git
      - php7.0
      - php7.0-mbstring
      - php7.0-sqlite3

  - name: Start Nginx service
    service: name=nginx enabled=yes state=started

#  tasks:
#  - git:
#    repo: 'https://github.com/linuxserver/Heimdall'
#    dest: /var/www/html
#    clone: yes