---
- hosts: all

  tasks:
  - name: Install Packages
    apt: name=nginx state=present
    with_items:
      - git
      - php7.0
      - php7.0-mbstring
      - php7.0-sqlite3
    when: ansible_os_family == "Debian"

  tasks:
  - name: Ensure Nginx is installed
        yum: name=nginx state=present
        when: ansible_os_family == "RedHat"


  - name: Start Nginx service
    service: name=nginx enabled=yes state=started

  tasks:
  - name: Clone Git Repo
  - git:
    repo: 'https://github.com/linuxserver/Heimdall'