---
- hosts: all

  pre_tasks:
  - name: Add Ansible PPA
    apt_repository:
      repo: 'ppa:ansible/ansible'

  - name: Update ansible to the latest version 
    apt:
      update_cache: yes
      name: ansible
      state: present

  - name: Install Packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
      - git
      - php7.0
      - php7.0-mbstring
      - php7.0-sqlite3
      - sqlite3
      - nginx

  - name: remove default index.html
    file:
      path: /var/www/html/index.nginx-debian.html
      state: absent

  - name: remove default index.html
    file:
      path: /etc/nginx/sites-available/default
      state: absent

#  - name: Clone Heimdall Git Repo 
#    git: repo='https://github.com/linuxserver/Heimdall' dest=/var/www/html clone=yes update=yes

  - name: 
    get_url:
      url: https://github.com/linuxserver/Heimdall/archive/v1.3.4.zip
      dest: ~/Heimdall

  - name: 
      unarchive:
        src: ~/Heimdall
        dest: /var/www/html
        mode: 0700
        owner: www-date

  - name: Add Symfony config template to the Nginx available sites
    become: true
    template:
      src: templates/nginx.conf
      dest: "/etc/nginx/sites-available/default"

  - name: Enable Symfony config template from Nginx available sites
    become: true
    file:
      src: "/etc/nginx/sites-available/default"
      dest: "/etc/nginx/sites-enabled/default"
      state: link

  - name: ensure php7.0-fpm cgi.fix_pathinfo=0
    lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
    notify:
#      - restart php7.0-fpm.service
#      - restart nginx

  roles:
    - role: geerlingguy.php
      php_version: "7.0"
      php_packages:
        - php7.0-common
        - php7.0-cli
        - php7.0-dev
        - php7.0-fpm
        - libpcre3-dev
        - php7.0-gd
        - php7.0-curl
        - php7.0-imap
        - php7.0-json
        - php7.0-opcache
        - php7.0-xml
        - php7.0-mbstring
      php_date_timezone: "America/Los_Angeles"
      php_mysql_package: php7.0-mysql
      php_fpm_daemon: php7.0-fpm
      php_webserver_daemon: "nginx"
      php_conf_paths:
        - /etc/php/7.0/fpm
        - /etc/php/7.0/apache2
        - /etc/php/7.0/cli
      php_extension_conf_paths:
        - /etc/php/7.0/fpm/conf.d
        - /etc/php/7.0/apache2/conf.d
        - /etc/php/7.0/cli/conf.d
      php_fpm_pool_conf_path: "/etc/php/7.0/fpm/pool.d/www.conf"  


  post_tasks:
    - name: Change owner for html directory
      file: dest=/var/www/html owner=www-data group=www-data mode=0700 recurse=yes
