---
- hosts: all

  pre_tasks:
  - name: Add Ansible PPA
    apt_repository:
      repo: 'ppa:ansible/ansible'

  pre_tasks:
  - name: Update ansible to the latest version 
    apt:
      update_cache: yes
      name: ansible
      state: present

  pre_tasks:
  - name: Install Packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
      - git
      - php7.0
      - php7.0-mbstring
      - php7.0-sqlite3
      - sqlite3
      - nginx
  - name: create /var/www/ directory
    file: dest=/var/www/ state=directory owner=www-data group=www-data mode=0700

  roles:
    - role: geerlingguy.php
      php_version: "7.0"
      php_packages:
        - php7.0-common
        - php7.0-cli
        - php7.0-dev
        - php7.0-fpm
        - libpcre3-dev
        - php7.0-gd
        - php7.0-curl
        - php7.0-imap
        - php7.0-json
        - php7.0-opcache
        - php7.0-xml
        - php7.0-mbstring
      php_date_timezone: "America/Los_Angeles"
      php_mysql_package: php7.0-mysql
      php_fpm_daemon: php7.0-fpm
      php_webserver_daemon: nginx
      php_conf_paths:
        - /etc/php/7.0/fpm
        - /etc/php/7.0/apache2
        - /etc/php/7.0/cli
      php_extension_conf_paths:
        - /etc/php/7.0/fpm/conf.d
        - /etc/php/7.0/apache2/conf.d
        - /etc/php/7.0/cli/conf.d
      php_fpm_pool_conf_path: "/etc/php/7.0/fpm/pool.d/www.conf"  
  tasks: 
    - name: Clone Heimdall Git Repo 
      git: repo='https://github.com/skluthe/Heimdall-playbook' dest=/var/www/html clone=yes update=yes

    - name: Move Heimdall to /var/www/html
      command: mv /var/www/html/Heimdall /var/www/html
